# Form implementation generated from reading ui file 'to_do.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 315)
        self.task_edit = QtWidgets.QLineEdit(parent=Form)
        self.task_edit.setGeometry(QtCore.QRect(90, 50, 113, 26))
        self.task_edit.setObjectName("task_edit")
        self.add_button = QtWidgets.QPushButton(parent=Form)
        self.add_button.setGeometry(QtCore.QRect(250, 50, 81, 26))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(parent=Form)
        self.delete_button.setGeometry(QtCore.QRect(370, 50, 81, 26))
        self.delete_button.setObjectName("delete_button")
        self.list_widget = QtWidgets.QListWidget(parent=Form)
        self.list_widget.setGeometry(QtCore.QRect(90, 100, 361, 192))
        self.list_widget.setObjectName("list_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_button.setText(_translate("Form", "Add"))
        self.delete_button.setText(_translate("Form", "Delete"))
